name: Release simple-krr-dashboard

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - Pipfile
      - Dockerfile

jobs:
  release:
    name: Create tag release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        id: semantic_release
        with:
          dry_run: false
          branch: main
          tag_format: v${version}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
